### ISSUE TITLE
[Suggestion] Add behaviour to Bunny Hood to make Young Link walk fast

### ISSUE THREAD

**Issue by ShadowOne333** [fig02/Better-OoT#18]
Like the title implies, I always thought that the Bunny Hood (and almost all the masks in OoT) are pretty meaningless overall, with their only purpose being to obtain the Mask of Truth, which also serves little purpose in the game outside of two items.

My suggestion is to add an option to make the Bunny Hood behave in the same way as it does on Majora's Mask, but in Ocarina of Time.
This will make traversing Hyrule Field as Young Link much less of a hassle, and it will also encourage people to try to complete the Masks side-quest before going for the Master Sword.

**Comment by fig02** [comment]
Hi
Thank you for your suggestion. I don't have plans to implement this because this is a tool created specifically for speedrunning. The idea is to not change any mechanics of actual gameplay as to keep the runs the same.

This has been discussed to be added to the randomizer, so maybe that will interest you. Not sure if it has actually been added though.

**Comment by ShadowOne333** [comment]
Hi! Thanks for the reply. I understand the main goal of this project.
With that said, does the Randomizer have such a mechanic already implemented?
If so, could you link me to it?
I'd like to implement it on my own to a fork of this project for sure, so that I can make my own custom build of Ocarina of Time.

Thanks in advance!

**Comment by fig02** [comment]
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/Dev/ASM/src/bunny_hood.asm

**Comment by ShadowOne333** [comment]
Oh nice!
I'll include that hack into my fork.
Thanks! :)

**Comment by ShadowOne333** [comment]
I noticed that the .asm files are all called inside the build.asm
Also, they all seem to be using a specific rom address.
Is there a way in which I can add the Bunny Hood ASM without causing overlapping DMA data records?
