### ISSUE TITLE
ROM won't load on emulator

### ISSUE THREAD

**Issue by werdna457** [fig02/Better-OoT#21]
I have an Ocarina of Time v1.0 ROM that works in my emulator, but when I use the BOoT wizard and try and load the result in my emulator, all I get is a black screen. I'm using the BOoT seed AQBAAAA and my emulator is Project64 with the default plugins. Is there something I'm doing wrong?

**Comment by fig02** [comment]
you need to enable 8mb of memory for expansion pak space

**Comment by werdna457** [comment]
> you need to enable 8mb of memory for expansion pak space

Thanks, worked like a charm
