### ISSUE TITLE
soft-lock

### ISSUE THREAD

**Issue by HenriqueJoao** [fig02/Better-OoT#7]
the game stays on a black screen after I play the song of storms in the windmill, the animation ends, and the i can't do anything, just stays on a black screen

**Comment by HenriqueJoao** [comment]
i play on Project 64 2.3

**Comment by fig02** [comment]
I believe this is a common issue with the randomizer (which this project is based off of). They always recommend people use other emulators like RetroArch.

Unfortunately, for this project my priority is console support, as this is mainly a speedrunning tool. Hopefully another emulator works out for you.

**Comment by krimtonz** [comment]
This issue is specifically with Project 64.
