### ISSUE TITLE
MQ Shadow Temple softlock?

### ISSUE THREAD

**Issue by xathian** [fig02/Better-OoT#8]
I am doing a MQ run and when I reach the very first room of Shadow Temple with the Truth Spinner the dialog text saying "Point my beak..." doesn't come up. Also, sometimes there are multiple real skulls on the poles and all together the area is impassable because even if you turn the bird toward the real skull the floor falls out and it plays the error sound.

I've even used a side hop to avoid the floor falling and tried pointing it toward all 5 poles in 1 life to prevent the reshuffle and it failed for all 5.

I am playing on Mupen64core Retroarch (Also tried on PJ64 and Mupen standalone)

**Comment by fig02** [comment]
Krimtonz identified the issue and submitted a fix https://github.com/fig02/Better-OoT/pull/9

The change will be included in the next release which is planned to come out after GDQ.
Thanks for the report!
